export const ActionTypes ={
  OPEN_USER_SECTION: 'OPEN_USER_SECTION',
  CLOSE_USER_SECTION: 'CLOSE_USER_SECTION',
  COMPLETE_USER_TASK: 'COMPLETE_USER_TASK',
  CLICK_ON_USER: 'CLICK_ON_USER',
  UPDATE_USER_AND_DATA: 'UPDATE_USER_AND_DATA',
  FETCH_USERS_SAGA: 'FETCH_USERS_SAGA',
  USERS_RECEIVED: 'USERS_RECEIVED',
};
