module.exports = {
  'plugins': [
    'lodash',
  ],
  'rules': {
    'lodash/callback-binding': 'error',
    'lodash/chain-style': ['error', 'as-needed'],
    'lodash/chaining': ['error', 'always', 3],
    'lodash/collection-method-value': 'error',
    'lodash/collection-return': 'error',
    'lodash/consistent-compose': ['error', 'flow'],
    'lodash/identity-shorthand': ['error', 'always'],
    'lodash/import-scope': 'off',
    'lodash/matches-prop-shorthand': 'off',
    'lodash/matches-shorthand': 'off',
    'lodash/no-commit': 'error',
    'lodash/no-double-unwrap': 'error',
    'lodash/no-extra-args': 'error',
    'lodash/no-unbound-this': 'error',
    'lodash/path-style': ['error', 'as-needed'],
    'lodash/prefer-compact': 'error',
    'lodash/prefer-constant': 'off',
    'lodash/prefer-filter': ['error', 3],
    'lodash/prefer-flat-map': 'error',
    'lodash/prefer-get': [ 'off' ],
    'lodash/prefer-includes': 'off',
    'lodash/prefer-invoke-map': 'off',
    'lodash/prefer-is-nil': 'off',
    'lodash/prefer-lodash-chain': 'off',
    'lodash/prefer-lodash-method': 'off',
    'lodash/prefer-lodash-typecheck': 'off',
    'lodash/prefer-map': 'error',
    'lodash/prefer-matches': ['error', 3],
    'lodash/prefer-noop': 'off',
    'lodash/prefer-over-quantifier': 'off',
    'lodash/prefer-reject': ['error', 3],
    'lodash/prefer-some': [ 'off' ],
    'lodash/prefer-startswith': 'off',
    'lodash/prefer-thru': 'error',
    'lodash/prefer-times': 'error',
    'lodash/prefer-wrapper-method': 'error',
    'lodash/preferred-alias': 'error',
    'lodash/prop-shorthand': 'off',
    'lodash/unwrap': 'error'
  },
};
