module.exports = {
  'plugins': [
    'react'
  ],
  'rules': {
    'react/display-name': 'off',
    'react/forbid-component-props': 'off',
    'react/forbid-prop-types': ['error', { 'forbid': ['any', 'array', 'object'] }],
    'react/jsx-boolean-value': ['error', 'never'],
    'react/jsx-closing-bracket-location': ['error', 'line-aligned'],
    'react/jsx-curly-spacing': ['error', 'never', { 'allowMultiline': true }],
    'react/jsx-equals-spacing': ['error', 'never'],
    'react/jsx-filename-extension': ['error', { 'extensions': [ '.js' ] }],
    'react/jsx-first-prop-new-line': ['error', 'multiline'],
    'react/jsx-handler-names': 'off',
    'react/jsx-indent-props': ['error', 2],
    'react/jsx-indent': ['error', 2],
    'react/jsx-key': 'off',
    'react/jsx-max-props-per-line': 'off',
    'react/jsx-no-bind': 'off',
    'react/jsx-no-comment-textnodes': 'off',
    'react/jsx-no-duplicate-props': ['error', {'ignoreCase': true}],
    'react/jsx-no-literals': 'off',
    'react/jsx-no-target-blank': 'error',
    'react/jsx-no-undef': 'error',
    'react/jsx-pascal-case': ['error', { allowAllCaps: false, ignore: []}],
    'react/jsx-sort-props': 'off',
    'react/jsx-tag-spacing': ['error', {
      'beforeSelfClosing': 'always',
    }],
    'react/jsx-uses-react': 'error',
    'react/jsx-uses-vars': 'error',
    'react/jsx-wrap-multilines': 'error',
    'react/no-children-prop': 'error',
    'react/no-danger': 'error',
    'react/no-danger-with-children': 'off',
    'react/no-deprecated': 'warn',
    'react/no-did-mount-set-state': 'error',
    'react/no-did-update-set-state': 'error',
    'react/no-direct-mutation-state': 'error',
    'react/no-find-dom-node': 'off',
    'react/no-is-mounted': 'error',
    'react/no-multi-comp': 'off',
    'react/no-render-return-value': 'error',
    'react/no-set-state': 'off',
    'react/no-string-refs': 'off',
    'react/no-unescaped-entities': 'off',
    'react/no-unknown-property': ['error', { ignore: [] }],
    'react/no-unused-prop-types': ['off', { skipShapeProps: false }],
    'react/prefer-es6-class': 'off',
    'react/prefer-stateless-function': 'off',
    'react/prop-types': ['error', { ignore: [], customValidators: [] }],
    'react/react-in-jsx-scope': 'error',
    'react/require-optimization': 'off',
    'react/require-render-return': 'error',
    'react/self-closing-comp': 'off',
    'react/sort-comp': 'off',
    'react/sort-prop-types': 'off',
    'react/style-prop-object': 'error',
  },
};
